### PR TITLE
Simplify go get installation by committing all dependencies

### PR DESCRIPTION
**Pull request by dencold**
Hi @jmhobbs this PR makes `terminal-parrot` installable directly via the `go get` command. I've committed all dependencies to the `vendor` directory which is the official way of handling this as of [Go 1.6](https://blog.golang.org/go1.6). I've used [glide](https://glide.sh/) as an easy way to manage dependencies going forward, but it isn't important. As long as the dependencies are in the `vendor` folder, you can now install terminal parrot with a simple `go get -u github.com/jmhobbs/terminal-parrot`.

I've updated the README to reflect this as well.

Thanks for keeping the party going!! ;)

### CODE REVIEW

**Comment by jmhobbs** [comment]
I'm not a gopher, but what's the advantage of pulling in vendor code for a project like this?

I just feel a bit odd having other projects code in my repo.  The changelog makes it sound like an option for dependencies, but not necessarily the blessed one.

Is this normative for small open source projects like this?

Just looking for guidance before merging in others code 😃

**Comment by dencold** [comment]
No worries. You have a dependency on the `github.com/nsf/termbox-go` package. Right now you explicitly require people to install that into their `GOPATH` in order for it to build. But what if nsf makes a breaking change to the api somewhere and breaks terminal-parrot? Or worse, say he pulls a [leftpad](http://arstechnica.com/information-technology/2016/03/rage-quit-coder-unpublished-17-lines-of-javascript-and-broke-the-internet/) and decides to remove termbox-go from github? Your project will no longer be able to build and **the party will be over** :cry: 

Clearly this isn't a mission critical project, and the chances of those two scenarios playing out are low, but I think the vendor directory serves an important purpose. You have everything you need, *always*, to build your project. It's akin to static vs. dynamic linking for the compiler.

Also, installation is a breeze now. If any user wants to run this on some architecture that isn't included in your binary releases, but they have Go installed, qll they need to do is enter one line into their terminal: `go get -u github.com/jmhobbs/terminal-parrot`, and they'll have the `terminal-parrot` binary installed.

party-or-what

**Comment by jmhobbs** [comment]
Sold!

**Comment by dencold** [comment]
Awesome!!! Thanks for this package in the first place, I :heart: party parrot!

**Pull request merged**
